language: cpp
dist: bionic
arch:
 - amd64
 - arm64

addons:
  apt:
    update: true
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-10 g++-10

env:
  global:
    - LIBRAW_GIT="git://github.com/LibRaw/LibRaw.git"
    - LIBRAW_GPL2_GIT="git://github.com/LibRaw/LibRaw-demosaic-pack-GPL2.git"
    - LIBRAW_GPL3_GIT="git://github.com/LibRaw/LibRaw-demosaic-pack-GPL3.git"
    - CC=gcc-10 CXX=g++-10

script:
  - cd ..
  - git clone $LIBRAW_GIT
  - git clone $LIBRAW_GPL2_GIT
  - git clone $LIBRAW_GPL3_GIT
  - cp -R LibRaw-cmake/* LibRaw
  - cp -R LibRaw-demosaic-pack-GPL2 LibRaw
  - cp -R LibRaw-demosaic-pack-GPL3 LibRaw
  - cd LibRaw
  - cmake . -DENABLE_DEMOSAIC_PACK_GPL2=ON -DENABLE_DEMOSAIC_PACK_GPL3=ON
  - make
  - sudo make install
