image: Visual Studio 2019

install:
  - cd ..
  - git clone --depth 1 https://github.com/LibRaw/LibRaw.git
  - git clone --depth 1 https://github.com/LibRaw/LibRaw-demosaic-pack-GPL2.git
  - git clone --depth 1 https://github.com/LibRaw/LibRaw-demosaic-pack-GPL3.git
  - git submodule update --init --recursive
  - xcopy LibRaw-cmake LibRaw /e/h/y/q
  - xcopy LibRaw-demosaic-pack-GPL2 LibRaw /e/h/y/q
  - xcopy LibRaw-demosaic-pack-GPL3 LibRaw /e/h/y/q
  - cd LibRaw
  - cmake . -DENABLE_DEMOSAIC_PACK_GPL2=ON -DENABLE_DEMOSAIC_PACK_GPL3=ON

build: off

artifacts:
 - path: LibRaw.sln
 - path: /**/LibRaw.sln
