image: Visual Studio 2019
configuration: Release

install:
  - git submodule update --init --recursive
  - cd ..
  - git clone --depth 1 https://github.com/LibRaw/LibRaw.git
  - git clone --depth 1 https://github.com/LibRaw/LibRaw-demosaic-pack-GPL2.git
  - git clone --depth 1 https://github.com/LibRaw/LibRaw-demosaic-pack-GPL3.git
  - xcopy LibRaw-cmake LibRaw /e/h/y/q
  - xcopy LibRaw-demosaic-pack-GPL2 LibRaw /e/h/y/q
  - xcopy LibRaw-demosaic-pack-GPL3 LibRaw /e/h/y/q
  - cd LibRaw
  - git submodule update --init --recursive
  - cmake . -DENABLE_DEMOSAIC_PACK_GPL2=ON -DENABLE_DEMOSAIC_PACK_GPL3=ON
  - xcopy C:\projects\LibRaw C:\projects\LibRaw-cmake /e/h/y/q

build:
 project: libraw.sln

artifacts:
 - path: libraw.sln
 - path: /**/libraw.sln
